# Generated by Django 2.2.4 on 2019-08-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucks',
            new_name='Truck',
        ),
    ]
